function RevenueChart({ data = [] }) {
    const safeData = Array.isArray(data) ? data : [];

    const maxValue = Math.max(
        ...safeData.map((item) => Number(item?.value) || 0),
        1
    );

    return (
        <div className="rounded-xl border border-slate-800 bg-slate-900 p-5">
            <div className="mb-6 flex items-center justify-between">
                <div>
                    <h3 className="text-sm font-semibold text-white">
                        Revenue Overview
                    </h3>

                    <p className="mt-1 text-xs text-slate-500">
                        Revenue generated by month
                    </p>
                </div>

                <span className="rounded-md bg-slate-800 px-2 py-1 text-[10px] text-slate-400">
                    Last 6 months
                </span>
            </div>

            {safeData.length === 0 ? (
                <div className="flex h-64 items-center justify-center">
                    <div className="text-center">
                        <p className="text-xs font-medium text-slate-400">
                            No revenue data available
                        </p>

                        <p className="mt-1 text-[10px] text-slate-600">
                            Revenue data will appear here when available.
                        </p>
                    </div>
                </div>
            ) : (
                <div className="flex h-64 items-end gap-3">
                    {safeData.map((item, index) => {
                        const value = Number(item?.value) || 0;

                        const height =
                            (value / maxValue) * 100;

                        return (
                            <div
                                key={item?.label || index}
                                className="flex h-full flex-1 flex-col items-center justify-end gap-2"
                            >
                                <span className="text-[9px] text-slate-500">
                                    ₹{value.toLocaleString("en-IN")}
                                </span>

                                <div className="flex h-full w-full items-end">
                                    <div
                                        className="w-full rounded-t-md bg-blue-600 transition-all duration-500 hover:bg-blue-500"
                                        style={{
                                            height: `${height}%`,
                                        }}
                                    />
                                </div>

                                <span className="text-[9px] text-slate-600">
                                    {item?.label || "—"}
                                </span>
                            </div>
                        );
                    })}
                </div>
            )}
        </div>
    );
}

export default RevenueChart;